"""field reports

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 23:47:05.737565

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_report_id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=True),
        sa.Column("place_name", sa.String(length=200), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("location_accuracy_m", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("submitted", "reviewed", "dismissed", name="report_status"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("hash_version", sa.Integer(), nullable=False),
        sa.Column("integrity_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "latitude BETWEEN 20.5 AND 26.7", name=op.f("ck_field_reports_latitude_in_bangladesh")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN 88.0 AND 92.7", name=op.f("ck_field_reports_longitude_in_bangladesh")
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_field_reports_reporter_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_reports")),
        sa.UniqueConstraint("reporter_id", "client_report_id", name="reporter_client_id"),
    )
    op.create_index(
        op.f("ix_field_reports_observed_at"), "field_reports", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_field_reports_received_at"), "field_reports", ["received_at"], unique=False
    )
    op.create_index(
        op.f("ix_field_reports_reporter_id"), "field_reports", ["reporter_id"], unique=False
    )
    op.create_table(
        "field_report_media",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("dhash", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["field_reports.id"],
            name=op.f("fk_field_report_media_report_id_field_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_report_media")),
    )
    op.create_index(
        op.f("ix_field_report_media_report_id"), "field_report_media", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_field_report_media_sha256"), "field_report_media", ["sha256"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_field_report_media_sha256"), table_name="field_report_media")
    op.drop_index(op.f("ix_field_report_media_report_id"), table_name="field_report_media")
    op.drop_table("field_report_media")
    op.drop_index(op.f("ix_field_reports_reporter_id"), table_name="field_reports")
    op.drop_index(op.f("ix_field_reports_received_at"), table_name="field_reports")
    op.drop_index(op.f("ix_field_reports_observed_at"), table_name="field_reports")
    op.drop_table("field_reports")
    # ### end Alembic commands ###
    sa.Enum(name="report_status").drop(op.get_bind(), checkfirst=True)
