"""events and evidence

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 00:57:54.491456

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("family", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "monitoring", "resolved", "dismissed", name="event_status"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "critical", name="event_priority"),
            nullable=False,
        ),
        sa.Column(
            "assessment",
            sa.Enum(
                "verified",
                "partially_verified",
                "conflicting",
                "unverified",
                "refuted",
                "insufficient_evidence",
                name="assessment_label",
            ),
            nullable=False,
        ),
        sa.Column("place_name", sa.String(length=200), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at", name=op.f("ck_events_ends_after_start")
        ),
        sa.CheckConstraint(
            "latitude BETWEEN 20.5 AND 26.7", name=op.f("ck_events_latitude_in_bangladesh")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN 88.0 AND 92.7", name=op.f("ck_events_longitude_in_bangladesh")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_events_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_family"), "events", ["family"], unique=False)
    op.create_index(op.f("ix_events_started_at"), "events", ["started_at"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_table(
        "event_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("field_report_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "supports", "partially_supports", "contradicts", "related", name="evidence_relation"
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("linked_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_evidence_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["field_report_id"],
            ["field_reports.id"],
            name=op.f("fk_event_evidence_field_report_id_field_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["linked_by_id"], ["users.id"], name=op.f("fk_event_evidence_linked_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_evidence")),
        sa.UniqueConstraint("event_id", "field_report_id", name="event_report_once"),
    )
    op.create_index(
        op.f("ix_event_evidence_event_id"), "event_evidence", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_evidence_field_report_id"),
        "event_evidence",
        ["field_report_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_evidence_field_report_id"), table_name="event_evidence")
    op.drop_index(op.f("ix_event_evidence_event_id"), table_name="event_evidence")
    op.drop_table("event_evidence")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_started_at"), table_name="events")
    op.drop_index(op.f("ix_events_family"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
    for name in ("evidence_relation", "assessment_label", "event_priority", "event_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
