"""field report review

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 20:40:48.805324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("field_reports", sa.Column("reviewed_by_id", sa.Uuid(), nullable=True))
    op.add_column(
        "field_reports", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("field_reports", sa.Column("review_note", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_field_reports_reviewed_by_id_users"),
        "field_reports",
        "users",
        ["reviewed_by_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_field_reports_reviewed_by_id_users"), "field_reports", type_="foreignkey"
    )
    op.drop_column("field_reports", "review_note")
    op.drop_column("field_reports", "reviewed_at")
    op.drop_column("field_reports", "reviewed_by_id")
    # ### end Alembic commands ###
