"""public signals

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 21:13:09.701408

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("news", "public_record", "other", name="source_type"),
            nullable=False,
        ),
        sa.Column(
            "adapter",
            sa.Enum("gdacs", "rss", "reliefweb", "manual", name="source_adapter"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("domain", sa.String(length=120), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("key", name=op.f("uq_sources_key")),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("fetched", sa.Integer(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_ingest_runs_source_id_sources")
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_id"], ["users.id"], name=op.f("fk_ingest_runs_triggered_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(op.f("ix_ingest_runs_source_id"), "ingest_runs", ["source_id"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "content_policy",
            sa.Enum("full", "excerpt", "reference_only", name="content_policy"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=True),
        sa.Column("family", sa.String(length=30), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("minor", "moderate", "severe", name="signal_severity"),
            nullable=True,
        ),
        sa.Column("place_name", sa.String(length=200), nullable=True),
        sa.Column("district", sa.String(length=60), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("precision_m", sa.Float(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.Enum("new", "reviewed", "dismissed", name="signal_status"), nullable=False
        ),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("entered_by_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "content_policy <> 'excerpt' OR char_length(coalesce(text, '')) <= 300",
            name=op.f("ck_signals_excerpt_is_short"),
        ),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)",
            name=op.f("ck_signals_both_coordinates_or_neither"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name=op.f("ck_signals_latitude_valid"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_signals_longitude_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["entered_by_id"], ["users.id"], name=op.f("fk_signals_entered_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name=op.f("fk_signals_reviewed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_signals_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("source_id", "external_id", name="source_item_once"),
    )
    op.create_index(op.f("ix_signals_collected_at"), "signals", ["collected_at"], unique=False)
    op.create_index(op.f("ix_signals_event_type"), "signals", ["event_type"], unique=False)
    op.create_index(op.f("ix_signals_published_at"), "signals", ["published_at"], unique=False)
    op.create_index(op.f("ix_signals_source_id"), "signals", ["source_id"], unique=False)
    op.create_index(op.f("ix_signals_status"), "signals", ["status"], unique=False)
    op.add_column("event_evidence", sa.Column("signal_id", sa.Uuid(), nullable=True))
    op.alter_column("event_evidence", "field_report_id", existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint("event_signal_once", "event_evidence", ["event_id", "signal_id"])
    op.create_index(
        op.f("ix_event_evidence_signal_id"), "event_evidence", ["signal_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_event_evidence_signal_id_signals"),
        "event_evidence",
        "signals",
        ["signal_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "one_kind_of_evidence", "event_evidence", "num_nonnulls(field_report_id, signal_id) = 1"
    )

    # Starting sources (a frozen copy: later code changes must not alter this migration).
    sources = sa.table(
        "sources",
        sa.column("id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("name", sa.String()),
        sa.column("source_type", sa.Enum(name="source_type", create_type=False)),
        sa.column("adapter", sa.Enum(name="source_adapter", create_type=False)),
        sa.column("url", sa.String()),
        sa.column("domain", sa.String()),
        sa.column("language", sa.String()),
        sa.column("enabled", sa.Boolean()),
        sa.column("interval_minutes", sa.Integer()),
    )
    op.bulk_insert(
        sources,
        [
            {
                "id": uuid.uuid4(),
                "key": key,
                "name": name,
                "source_type": stype,
                "adapter": adapter,
                "url": url,
                "domain": domain,
                "language": lang,
                "enabled": enabled,
                "interval_minutes": every,
            }
            for key, name, stype, adapter, url, domain, lang, enabled, every in SEED_SOURCES
        ],
    )


SEED_SOURCES = [
    ("gdacs", "GDACS disaster alerts", "public_record", "gdacs",
     "https://www.gdacs.org/xml/rss.xml", "gdacs.org", "en", True, 30),
    ("prothomalo-en", "Prothom Alo English", "news", "rss",
     "https://en.prothomalo.com/feed/", "en.prothomalo.com", "en", True, 30),
    ("prothomalo-bn", "Prothom Alo", "news", "rss",
     "https://www.prothomalo.com/feed/", "prothomalo.com", "bn", True, 30),
    ("dailystar", "The Daily Star", "news", "rss",
     "https://www.thedailystar.net/frontpage/rss.xml", "thedailystar.net", "en", True, 60),
    ("reliefweb", "ReliefWeb (Bangladesh)", "public_record", "reliefweb",
     "https://api.reliefweb.int/v2/reports", "reliefweb.int", "en", False, 120),
    ("bmd", "Bangladesh Meteorological Department", "public_record", "manual",
     None, "bmd.gov.bd", "en", True, 0),
    ("ffwc", "Flood Forecasting and Warning Centre", "public_record", "manual",
     None, "ffwc.gov.bd", "en", True, 0),
]  # fmt: skip


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM event_evidence WHERE signal_id IS NOT NULL")
    op.drop_constraint(
        op.f("ck_event_evidence_one_kind_of_evidence"), "event_evidence", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_event_evidence_signal_id_signals"), "event_evidence", type_="foreignkey"
    )
    op.drop_index(op.f("ix_event_evidence_signal_id"), table_name="event_evidence")
    op.drop_constraint("event_signal_once", "event_evidence", type_="unique")
    op.alter_column("event_evidence", "field_report_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("event_evidence", "signal_id")
    op.drop_index(op.f("ix_signals_status"), table_name="signals")
    op.drop_index(op.f("ix_signals_source_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_published_at"), table_name="signals")
    op.drop_index(op.f("ix_signals_event_type"), table_name="signals")
    op.drop_index(op.f("ix_signals_collected_at"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_ingest_runs_source_id"), table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("sources")
    # ### end Alembic commands ###
    for name in ("signal_status", "signal_severity", "content_policy", "source_adapter",
                 "source_type"):  # fmt: skip
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
