"""backfill windows

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-04 00:30:26.253426

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingest_runs", sa.Column("window_start", sa.Date(), nullable=True))
    op.add_column("ingest_runs", sa.Column("window_end", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingest_runs", "window_end")
    op.drop_column("ingest_runs", "window_start")
    # ### end Alembic commands ###
